### ISSUE TITLE
Error during maven compilation

### ISSUE THREAD

**Issue by armandossrecife** [ashykhmat/jMetrics#14]
Myenvironment:
MacOS Mojave 10.14.6
java version: java 11.0.11 2021-04-20 LTS

1. The repository was cloned

2. Go to main directory ../jMetrics

3. Run maven command
`mvn clean install`

4. The following message are shown as a result: 
`
[INFO] Surefire report directory: /Users/armandosoaressousa/Desenvolvimento/metrics/jMetrics/jmetrics-core/target/surefire-reports
 T E S T S
Running com.shykhmat.jmetrics.core.report.postprocessor.PackageReportPostProcessorTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.166 sec
Running com.shykhmat.jmetrics.core.report.postprocessor.ClassReportPostProcessorTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec <<< FAILURE!
testProcessing(com.shykhmat.jmetrics.core.report.postprocessor.ClassReportPostProcessorTest)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <[com.shykhmat.all.All, Unknown, com.shykhmat.D]>
     but: was <[All, Unknown, com.shykhmat.D]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.shykhmat.jmetrics.core.report.postprocessor.ClassReportPostProcessorTest.lambda$assertReports$1(ClassReportPostProcessorTest.java:64)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.shykhmat.jmetrics.core.report.postprocessor.ClassReportPostProcessorTest.assertReports(ClassReportPostProcessorTest.java:57)
	at com.shykhmat.jmetrics.core.report.postprocessor.ClassReportPostProcessorTest.testProcessing(ClassReportPostProcessorTest.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running com.shykhmat.jmetrics.core.metric.cyclomatic.CyclomaticComplexityCalculatorTest
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.853 sec
Running com.shykhmat.jmetrics.core.metric.loc.LinesOfCodeCalculatorTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.048 sec
Running com.shykhmat.jmetrics.core.metric.halstead.HalsteadComplexityCalculatorTest
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.129 sec
Running com.shykhmat.jmetrics.core.metric.coupling.CircularDependenciesCalculatorTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec
Running com.shykhmat.jmetrics.core.metric.coupling.EfferentCouplingVisitorTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.117 sec

Results :

Failed tests:   testProcessing(com.shykhmat.jmetrics.core.report.postprocessor.ClassReportPostProcessorTest): (..)

Tests run: 30, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] jMetrics ........................................... SUCCESS [ 42.451 s]
[INFO] jMetrics Build Tools ............................... SUCCESS [  1.001 s]
[INFO] jMetrics Core ...................................... FAILURE [ 53.273 s]
[INFO] jMetrics Sonar Plug-in ............................. SKIPPED
[INFO] jMetrics Console Application ....................... SKIPPED
[INFO] jMetrics Maven Plug-in ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:43 min
[INFO] Finished at: 2021-06-09T15:10:09-03:00
[INFO] Final Memory: 43M/154M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project jmetrics-core: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/armandosoaressousa/Desenvolvimento/metrics/jMetrics/jmetrics-core/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jmetrics-core
`

**Comment by ashykhmat** [comment]
Issue is fixed in the latest version
